<?php
/**
 * TL_ROOT/system/modules/morelinks/languages/it/default.php 
 * 
 * Contao extension: morelinks 1.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2009 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['pickerFiles'] = "Sfoglia";
$GLOBALS['TL_LANG']['MSC']['pickerNews'] = "News";
$GLOBALS['TL_LANG']['MSC']['pickerEvents'] = "Eventi";
$GLOBALS['TL_LANG']['MSC']['pickerFAQ'] = "Faq";
 
?>
